RandomForest:
     model__n_estimators: [100, 300, 500]
     model__max_depth: [10, 15, 20, 25, 30]
     model__min_samples_split: [2, 5, 10, 15, 50]
     model__min_samples_leaf: [1, 2, 5, 10]
     model__bootstrap: [True, False]
     model__criterion: ['gini', 'entropy']

LogitRegression:
     model__C: [0.001, 0.01, 0.1, 0.25, 0.5, 1, 10, 100]
     model__max_iter: [200, 400, 600]
     model__solver: ['newton-cg', 'sag', 'lbfgs']
     model__fit_intercept: [False, True]
     model__penalty: ['l2']
     model__dual: [False]
